baseURL: "https://fmuyassarov.github.io/"
title: Blog posts
paginate: 5
theme: hugo-PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true

minify:
    disableXML: true

menu:
    main:
        - name: Archive
          url: https://fmuyassarov.github.io/archives/
          weight: 5
        - name: Tags
          url: https://fmuyassarov.github.io/tags/
          weight: 10
        - name: Blogs
          url: https://fmuyassarov.github.io/blogs/
          weight: 10
        - name: Home
          url: /
          weight: 10

outputs:
    home:
        - HTML
        - RSS
        - JSON

params:
    env: production
    defaultTheme: auto
    ShowShareButtons: true
    ShowReadingTime: true
    displayFullLangName: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    ShowToc: true
    homeInfoParams:
        Title: "Feruzjon Muyassarov"
        Content: >
            - Hi there! I'm Feruzjon Muyassarov, or @fmuyassarov on the internet.

            - I am a cloud orchestration developer at Intel, focusing on Kubernetes resource management

    socialIcons:
        - name: github
          url: "https://github.com/fmuyassarov"
        - name: linkedin
          url: "https://www.linkedin.com/in/feruzjon-muyassarov/"
        - name: credly
          url: "https://www.credly.com/users/fmuyassarov"
        - name: youtube
          url: "https://www.youtube.com/@fmuyassarov"
        - name: twitter
          url: "https://twitter.com/fmuyassarov"

    editPost:
        URL: "https://github.com/fmuyassarov/fmuyassarov.github.io"
        Text: "Suggest Changes"
        appendFilePath: true

taxonomies:
    category: categories
    tag: tags
    series: series

markup:
    goldmark:
        renderer:
            unsafe: true
